### ISSUE TITLE
Some digits are consistently returned as * with the Android SDK.

### ISSUE THREAD

**Issue by fofx** [DoubangoTelecom/ultimateMICR-SDK#51] opened 2022-01-18 22:06 UTC
When running the MICR  e13b detection in my own app and the provided sample app, certain digits are consistently returned as an asterisk '*'. 

I am using the provided sample images from here: https://www.doubango.org/webapps/micr/

When scanning one of the images here is my outcome:
Expected: C370694CA102000979A68008192429291C
Actual: C370*94CA10*000979A**00*19*4*9*91C

It looks like digits 2, 6, and 8 are the ones creating issues for me.

I played around with different configuration settings, but have had no luck. Is there something I'm missing?

**Comment by fofx** [comment] 2022-01-18 22:11
My mistake - I've found the license restrictions. Will there eventually be a license for MICR detection per application?

**Comment by DoubangoTelecom** [comment] 2022-01-18 22:47
Duplicate of #42

**Closed by DoubangoTelecom** 2022-01-18 22:47 UTC
